# Generated by Django 4.2 on 2024-02-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botAdmin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacemeeting",
            name="date",
            field=models.CharField(max_length=200, verbose_name="Дата и время встречи"),
        ),
    ]
